name: Dart
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: flutter test test/util/StringUtil_test.dart
